@extends('adminlte::page')

@section('title', 'Paramètres entreprise')

@section('content')
<div class="container-fluid py-3">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('enterprise.settings.update') }}" enctype="multipart/form-data">
        @csrf @method('PUT')
        <div class="card card-primary card-outline"><div class="card-header"><h3 class="card-title">Informations de l'entreprise</h3></div><div class="card-body"><div class="row"><div class="col-md-6 form-group"><label>Nom</label><input class="form-control" name="name" value="{{ old('name', $entreprise->name) }}" required></div><div class="col-md-6 form-group"><label>Email</label><input class="form-control" type="email" name="email" value="{{ old('email', $entreprise->email) }}"></div><div class="col-md-6 form-group"><label>Téléphone</label><input class="form-control" name="tel" value="{{ old('tel', $entreprise->tel) }}"></div><div class="col-md-6 form-group"><label>ICE</label><input class="form-control" name="ice" value="{{ old('ice', $entreprise->ice) }}"></div><div class="col-12 form-group"><label>Adresse</label><input class="form-control" name="adresse" value="{{ old('adresse', $entreprise->adresse) }}"></div></div></div></div>
        <div class="card card-primary card-outline"><div class="card-header"><h3 class="card-title">Identité visuelle et documents</h3></div><div class="card-body"><div class="row"><div class="col-md-6 form-group"><label>Logo</label><input class="form-control-file d-block" type="file" name="logo" accept="image/jpeg,image/png,image/jpg,image/webp">@if($entreprise->logo)<img class="mt-2" src="{{ asset('storage/'.$entreprise->logo) }}" style="max-height:80px" alt="Logo">@endif</div><div class="col-md-6 form-group"><label>Arrière-plan des documents</label><input class="form-control-file d-block" type="file" name="document_background" accept="image/jpeg,image/png,image/jpg,image/webp">@if($entreprise->document_background)<img class="mt-2" src="{{ asset('storage/'.$entreprise->document_background) }}" style="max-height:80px" alt="Arrière-plan">@endif</div><div class="col-md-4 form-group"><label>Position du logo</label><select class="form-control" name="document_logo_position"><option value="left" @selected(old('document_logo_position', $entreprise->document_logo_position ?: 'left') === 'left')>Gauche</option><option value="center" @selected(old('document_logo_position', $entreprise->document_logo_position) === 'center')>Centre</option><option value="right" @selected(old('document_logo_position', $entreprise->document_logo_position) === 'right')>Droite</option></select></div><div class="col-md-4 form-group"><label>Couleur principale</label><input class="form-control" type="color" name="document_primary_color" value="{{ old('document_primary_color', $entreprise->document_primary_color ?: '#315EFB') }}"></div><div class="col-md-4 form-group"><label>Couleur secondaire</label><input class="form-control" type="color" name="document_secondary_color" value="{{ old('document_secondary_color', $entreprise->document_secondary_color ?: '#64748B') }}"></div></div></div></div>
        <button class="btn btn-primary" type="submit"><i class="fas fa-save mr-1"></i>Enregistrer</button>
    </form>
</div>
@endsection
