<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Centralisez vos produits, stocks et opérations commerciales avec Gestion Stock.">
<meta name="theme-color" content="#f7f9ff"><title>Gestion Stock — Gérez votre stock en toute simplicité</title>
<link rel="icon" href="{{ asset('favicon.ico') }}"><link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}">
<style>
:root{--blue:#09f;--dark:#2449d8;--ink:#15213b;--muted:#69758d;--line:#e8edf5;--pale:#f6f8ff}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:88px}body{margin:0;color:var(--ink);font-family:Inter,"Segoe UI",Arial,sans-serif;-webkit-font-smoothing:antialiased}a{color:inherit;text-decoration:none}.wrap{width:min(1160px,calc(100% - 48px));margin:auto}
header{position:sticky;top:0;z-index:5;background:#fffffff2;border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}.nav{height:76px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:11px;font-weight:750;letter-spacing:-.03em}.brand-icon{width:39px;height:39px;display:grid;place-items:center;border-radius:12px;color:white;background:linear-gradient(145deg,#4776ff,#3153dc);box-shadow:0 7px 18px #315efb35}.links,.nav-actions{display:flex;align-items:center;gap:26px}.links{color:#58647c;font-size:.9rem;font-weight:600}.links a:hover,footer a:hover{color:var(--blue)}.nav-actions{gap:8px}.btn{display:inline-flex;justify-content:center;align-items:center;gap:9px;padding:13px 18px;border-radius:10px;font-size:.88rem;font-weight:700;transition:transform .2s,background .2s,box-shadow .2s}.btn:hover{transform:translateY(-2px)}.primary{color:white;background:var(--blue);box-shadow:0 9px 22px #315efb32}.primary:hover{color:white;background:var(--dark)}.light{background:white;border:1px solid var(--line);color:#26334e}.text-btn{padding:10px;color:#53617a}
.hero{position:relative;overflow:hidden;padding:82px 0 92px;background:radial-gradient(ellipse at 83% 25%,#dce6ff,transparent 36%),linear-gradient(#f8faff,#fff)}.hero-grid{display:grid;grid-template-columns:.9fr 1.1fr;align-items:center;gap:54px}.eyebrow{color:var(--blue);font-size:.75rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.eyebrow i{margin-right:7px;font-size:.55rem}h1,h2,h3{letter-spacing:-.045em}h1{max-width:620px;margin:18px 0;font-size:clamp(2.7rem,5.2vw,4.5rem);line-height:1.04}h1 span{color:var(--blue)}.copy{max-width:540px;color:var(--muted);font-size:1.08rem;line-height:1.8}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:27px}.note{margin-top:19px;color:#748098;font-size:.82rem}.note i{margin-right:8px;color:#20a577}
.visual{position:relative;padding:18px 12px 28px 20px}.dashboard{overflow:hidden;padding:12px;background:white;border:1px solid #e2e8f4;border-radius:17px;box-shadow:0 32px 75px #263a711f;transform:rotate(.7deg);animation:float 6s ease-in-out infinite}.browser{padding:4px 8px 13px;color:#97a2b6;font-size:.64rem}.dot{display:inline-block;width:7px;height:7px;margin-right:5px;border-radius:50%;background:#d7deeb}.browser span{margin-left:7px}.app{display:grid;grid-template-columns:120px 1fr;min-height:330px;overflow:hidden;border-radius:10px;background:#f6f8fc}.side{padding:17px 9px;background:#172443;color:#aab5cb}.side b{display:block;margin:1px 4px 22px;color:white;font-size:.64rem}.side div{margin:4px 0;padding:9px 7px;border-radius:6px;font-size:.56rem}.side .active{color:white;background:var(--blue)}.side i{width:16px}.main{min-width:0;padding:17px}.main-head{display:flex;justify-content:space-between;margin-bottom:15px}.main-head strong{font-size:.9rem}.main-head small{color:#95a0b4;font-size:.56rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.stat,.panel{padding:11px;background:white;border:1px solid #edf0f6;border-radius:8px}.stat i{display:block;margin-bottom:8px;color:var(--blue)}.stat small{display:block;color:#8995aa;font-size:.51rem}.stat b{display:block;margin-top:5px;font-size:.69rem}.lower{display:grid;grid-template-columns:1.2fr .8fr;gap:9px;margin-top:9px}.panel{min-width:0;padding:11px}.panel-title{margin-bottom:13px;color:#66738c;font-size:.57rem;font-weight:700}.chart{height:105px;display:flex;align-items:end;gap:8px;padding:6px 3px 0;border-bottom:1px solid #edf0f6;background:repeating-linear-gradient(to bottom,transparent 0 25px,#f0f3f8 26px)}.bar{flex:1;min-width:4px;border-radius:3px 3px 0 0;background:#dce5ff}.bar:nth-child(3n){background:#7d99ff}.bar:nth-child(4){background:var(--blue)}.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f0f2f6;color:#68758d;font-size:.54rem}.row i{color:#159467}.float-card{position:absolute;right:-3px;bottom:0;display:flex;align-items:center;gap:10px;padding:12px 14px;background:white;border:1px solid #edf0f6;border-radius:12px;box-shadow:0 14px 32px #263a7117;font-size:.72rem}.float-card i{color:#159467}.float-card small{display:block;margin-top:4px;color:#8a96a9;font-size:.61rem}
.trust{border-block:1px solid #f0f2f7}.trust-in{display:flex;justify-content:center;flex-wrap:wrap;gap:20px 42px;padding:20px 0;color:#78849b;font-size:.82rem}.trust i{margin-right:7px;color:var(--blue)}.section{padding:88px 0}.soft{background:#f7f9fd}.section-head{max-width:650px;margin:0 auto 40px;text-align:center}.section-head h2,.about h2{margin:13px 0;font-size:clamp(2rem,3.7vw,3rem);line-height:1.12}.section-head p,.about-copy{color:var(--muted);line-height:1.75}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.feature{padding:24px;background:white;border:1px solid var(--line);border-radius:15px;box-shadow:0 7px 23px #22365b08;transition:transform .2s,box-shadow .2s}.feature:hover{transform:translateY(-4px);box-shadow:0 16px 32px #22365b12}.ico{width:45px;height:45px;display:grid;place-items:center;margin-bottom:17px;border-radius:13px;background:#eef2ff;color:var(--blue)}.feature h3{margin:0 0 8px;font-size:1.04rem}.feature p{margin:0;color:var(--muted);font-size:.89rem;line-height:1.7}
.about-grid{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:70px}.about h2{margin:14px 0}.benefits{display:grid;gap:17px;margin-top:24px}.benefit{display:flex;gap:12px}.check{flex:0 0 25px;width:25px;height:25px;display:grid;place-items:center;border-radius:50%;background:#e9f8f1;color:#149668;font-size:.68rem}.benefit strong{display:block;margin-bottom:4px;font-size:.93rem}.benefit p{margin:0;color:var(--muted);font-size:.85rem;line-height:1.6}.about-card{padding:28px;border:1px solid #e5eaf4;border-radius:20px;background:linear-gradient(145deg,#f3f6ff,#fff);box-shadow:0 20px 55px #29427412}.about-card h3{margin:0 0 5px}.about-card>p{margin:0 0 20px;color:var(--muted);font-size:.8rem}.flow{display:grid;gap:10px}.flow div{display:flex;align-items:center;gap:12px;padding:13px;background:white;border:1px solid #edf0f5;border-radius:11px}.flow i{width:32px;color:var(--blue)}.flow span{font-size:.84rem;font-weight:650}
.cta{padding:52px 25px;border-radius:22px;text-align:center;color:white;background:radial-gradient(ellipse at 85% 5%,#6383ff,transparent 35%),linear-gradient(120deg,#193cae,#315efb)}.cta h2{margin:0 auto 12px;font-size:clamp(1.9rem,4vw,2.8rem)}.cta p{max-width:590px;margin:0 auto 23px;color:#e0e7ff;line-height:1.7}.cta .btn{background:white;color:#2449cf}footer{padding:30px 0;border-top:1px solid var(--line)}.footer-in{display:flex;align-items:center;justify-content:space-between;gap:22px}.footer-brand small{display:block;margin-top:8px;color:#8390a5;font-size:.75rem}.footer-links{display:flex;flex-wrap:wrap;gap:19px;color:#68758d;font-size:.81rem}.copyright{color:#8b96a9;font-size:.76rem}
@keyframes float{0%,100%{transform:rotate(.7deg) translateY(0)}50%{transform:rotate(.7deg) translateY(-7px)}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation:none!important;transition:none!important}}@media(max-width:900px){.links{gap:14px}.hero-grid{grid-template-columns:1fr;gap:32px}.visual{width:min(650px,100%);margin:auto}.features{grid-template-columns:repeat(2,1fr)}.about-grid{gap:36px}.trust-in{gap:16px 22px}}@media(max-width:640px){.wrap{width:calc(100% - 34px)}.nav{height:66px}.links{display:none}.nav-actions{gap:2px}.btn{padding:11px 12px;font-size:.79rem}.hero{padding:56px 0 64px}h1{font-size:clamp(2.55rem,11vw,3.5rem)}.copy{font-size:1rem}.visual{padding:6px 0 22px}.dashboard{padding:7px;transform:none;animation:none}.app{grid-template-columns:77px 1fr;min-height:260px}.side{padding:12px 5px}.side b{font-size:.5rem}.side div{padding:8px 4px;font-size:.47rem}.main{padding:12px 8px}.stats{gap:4px}.stat{padding:8px 5px}.stat small{font-size:.43rem}.stat b{font-size:.57rem}.lower{gap:5px}.panel{padding:8px}.chart{height:79px;gap:5px}.float-card{right:-4px;bottom:-1px}.section{padding:65px 0}.features{grid-template-columns:1fr;gap:11px}.feature{padding:21px}.about-grid{grid-template-columns:1fr;gap:27px}.about-card{padding:22px}.cta{padding:39px 18px}.footer-in{align-items:flex-start;flex-direction:column}.footer-links{gap:12px 17px}}
</style>
</head>
<body>
<header><nav class="wrap nav" aria-label="Navigation principale">
<a class="brand" href="#accueil"><span class="brand-icon"><i class="fas fa-boxes-stacked"></i></span>Gestion Stock</a>
<div class="links"><a href="#accueil">Accueil</a><a href="#fonctionnalites">Fonctionnalités</a><a href="#a-propos">À propos</a><a href="#contact">Contact</a></div>
<div class="nav-actions">@auth<a class="btn text-btn" href="{{ route('dashboard') }}">Mon espace</a>@else<a class="btn text-btn" href="{{ route('login') }}">Se connecter</a><a class="btn primary" href="{{ route('register') }}">Commencer <i class="fas fa-arrow-right"></i></a>@endauth</div>
</nav></header>
<main>
<section class="hero" id="accueil"><div class="wrap hero-grid"><div>
<div class="eyebrow"><i class="fas fa-circle"></i> Gestion de Stock · La solution complète pour votre entreprise</div>
<h1>Gérez votre stock <span>en toute simplicité</span></h1>
<p class="copy">Une solution complète pour gérer vos produits, vos ventes, vos achats et vos factures depuis une seule plateforme.</p>
<div class="actions">@auth<a class="btn primary" href="{{ route('dashboard') }}">Accéder à l’application <i class="fas fa-arrow-right"></i></a>@else<a class="btn primary" href="{{ route('register') }}">Commencer maintenant <i class="fas fa-arrow-right"></i></a>@endauth<a class="btn light" href="#fonctionnalites"><i class="fas fa-play"></i> Découvrir les fonctionnalités</a></div>
<div class="note"><i class="fas fa-circle-check"></i> Vos opérations essentielles réunies dans un seul espace.</div>
</div>
<div class="visual" role="img" aria-label="Illustration d’un tableau de bord de gestion de stock"><div class="dashboard"><div class="browser"><i class="dot"></i><i class="dot"></i><i class="dot"></i><span>gestion-stock.app / tableau de bord</span></div><div class="app">
<aside class="side"><b>GESTION STOCK</b><div class="active"><i class="fas fa-grip"></i>Vue d’ensemble</div><div><i class="fas fa-box"></i>Produits</div><div><i class="fas fa-users"></i>Clients</div><div><i class="fas fa-file-invoice"></i>Factures</div><div><i class="fas fa-cart-shopping"></i>Achats</div></aside>
<div class="main"><div class="main-head"><strong>Vue d’ensemble</strong><small>Votre espace de gestion</small></div><div class="stats"><div class="stat"><i class="fas fa-boxes-stacked"></i><small>Produits</small><b>Catalogue</b></div><div class="stat"><i class="fas fa-file-invoice-dollar"></i><small>Documents</small><b>Factures & devis</b></div><div class="stat"><i class="fas fa-arrow-right-arrow-left"></i><small>Activité</small><b>Mouvements</b></div></div>
<div class="lower"><div class="panel"><div class="panel-title">Suivi de votre activité</div><div class="chart" aria-hidden="true"><i class="bar" style="height:35%"></i><i class="bar" style="height:58%"></i><i class="bar" style="height:45%"></i><i class="bar" style="height:77%"></i><i class="bar" style="height:61%"></i><i class="bar" style="height:88%"></i><i class="bar" style="height:70%"></i><i class="bar" style="height:96%"></i></div></div><div class="panel"><div class="panel-title">Gestion centralisée</div><div class="row"><span>Produits</span><i class="fas fa-check"></i></div><div class="row"><span>Clients</span><i class="fas fa-check"></i></div><div class="row"><span>Achats</span><i class="fas fa-check"></i></div></div></div></div></div><div class="float-card"><i class="fas fa-chart-line"></i><span>Une activité mieux suivie<small>Les informations à portée de main</small></span></div></div></div></section>
<div class="trust"><div class="wrap trust-in"><span><i class="fas fa-box"></i>Produits & stocks</span><span><i class="fas fa-file-invoice"></i>Documents commerciaux</span><span><i class="fas fa-handshake"></i>Clients & fournisseurs</span><span><i class="fas fa-cart-shopping"></i>Ventes & achats</span></div></div>
<section class="section" id="fonctionnalites"><div class="wrap"><div class="section-head"><div class="eyebrow">Tout au même endroit</div><h2>Les outils essentiels à votre activité</h2><p>Organisez votre gestion commerciale avec des fonctionnalités pensées pour simplifier le quotidien.</p></div><div class="features">
<article class="feature"><div class="ico"><i class="fas fa-boxes-stacked"></i></div><h3>Produits et stocks</h3><p>Centralisez votre catalogue, vos catégories et vos niveaux de stock.</p></article>
<article class="feature"><div class="ico"><i class="fas fa-address-book"></i></div><h3>Clients et fournisseurs</h3><p>Retrouvez facilement les informations de vos partenaires commerciaux.</p></article>
<article class="feature"><div class="ico"><i class="fas fa-file-signature"></i></div><h3>Devis et commandes</h3><p>Préparez et suivez vos documents commerciaux depuis un espace unique.</p></article>
<article class="feature"><div class="ico"><i class="fas fa-receipt"></i></div><h3>Ventes et factures</h3><p>Gérez vos ventes et rassemblez les documents associés à vos clients.</p></article>
<article class="feature"><div class="ico"><i class="fas fa-cart-flatbed"></i></div><h3>Gestion des achats</h3><p>Organisez vos achats et commandes auprès de vos fournisseurs.</p></article>
<article class="feature"><div class="ico"><i class="fas fa-arrow-right-arrow-left"></i></div><h3>Mouvements de stock</h3><p>Consultez l’historique des mouvements pour suivre votre inventaire.</p></article>
</div></div></section>
<section class="section soft" id="a-propos"><div class="wrap about-grid"><div class="about"><div class="eyebrow">Une gestion plus fluide</div><h2>Gardez une vue claire sur votre activité</h2><p class="about-copy">Retrouvez vos opérations commerciales dans une interface conçue pour rendre la gestion quotidienne plus simple et plus lisible.</p><div class="benefits">
<div class="benefit"><span class="check"><i class="fas fa-check"></i></span><div><strong>Centralisez vos opérations</strong><p>Produits, partenaires et documents sont réunis dans la même application.</p></div></div>
<div class="benefit"><span class="check"><i class="fas fa-check"></i></span><div><strong>Suivez vos stocks et mouvements</strong><p>Consultez les informations de stock et l’historique des mouvements disponibles.</p></div></div>
<div class="benefit"><span class="check"><i class="fas fa-check"></i></span><div><strong>Gagnez du temps au quotidien</strong><p>Accédez rapidement aux outils utiles avec une interface simple à prendre en main.</p></div></div>
</div></div><div class="about-card"><h3><i class="fas fa-layer-group"></i> &nbsp;Une plateforme, vos opérations</h3><p>Une organisation claire pour votre gestion</p><div class="flow"><div><i class="fas fa-boxes-stacked"></i><span>Catalogue et inventaire</span></div><div><i class="fas fa-people-arrows-left-right"></i><span>Relations commerciales</span></div><div><i class="fas fa-file-lines"></i><span>Documents et transactions</span></div><div><i class="fas fa-truck-ramp-box"></i><span>Approvisionnement</span></div></div></div></div></section>
<section class="section" id="contact"><div class="wrap"><div class="cta"><h2>Prêt à simplifier votre gestion&nbsp;?</h2><p>Connectez-vous à votre espace ou créez votre compte pour commencer à centraliser votre activité.</p>@auth<a class="btn" href="{{ route('dashboard') }}">Accéder à l’application <i class="fas fa-arrow-right"></i></a>@else<a class="btn" href="{{ route('register') }}">Commencer maintenant <i class="fas fa-arrow-right"></i></a>@endauth</div></div></section>
</main>
<footer><div class="wrap footer-in"><div class="footer-brand"><a class="brand" href="#accueil"><span class="brand-icon"><i class="fas fa-boxes-stacked"></i></span>Gestion Stock</a><small>Une gestion simple et centralisée pour votre activité.</small></div><nav class="footer-links" aria-label="Pied de page"><a href="#accueil">Accueil</a><a href="#fonctionnalites">Fonctionnalités</a><a href="#a-propos">À propos</a><a href="#contact">Contact</a><a href="{{ route('login') }}">Se connecter</a></nav><div class="copyright">© {{ date('Y') }} Gestion Stock</div></div></footer>
</body></html>
